/*
Copyright (c) 2013 Andrey Penechko

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license the "Software" to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module anchovy.graphics.camera;

// Magic bug like in shaderprogram.d
//import dlib.math.matrix4x4;
import dlib.math.vector;

class Camera
{
public:
	/*this()
	{
		UpdatePerspective();
	}
		
	this(float fov ,
		 float aspect,
		 float near,
		 float far)
	{
		_fov	= fov;
		_aspect	= aspect;
		_near	= near;
		_far	= far;
		UpdatePerspective();
	}
	
	Matrix4x4f UpdatePerspective()
	{
		perspective = perspectiveMatrix(_fov, _aspect, _near, _far);
		return perspective;
	}
	
	@property {
		float fov(){ return fov; }
		float fov(float newFov){ return _fov = newFov; }
		
		float aspect(){ return fov; }
		float aspect(float newAspect){ return _aspect = newAspect; }
		
		float near(){ return fov; }
		float near(float newNear){ return _near = newNear; }
		
		float far(){ return fov; }
		float far(float newFar){ return _far = newFar; }
	}

	
	Matrix4x4f perspective;
	Vector3f	position 	= vec3(0, 0, 0);
	Vector3f	target 		= vec3(0, 0, 1);
	Vector3f	up			= vec3(0, 1, 0);
	
	private :
		float _fov = 60, _aspect = 1, _near = 0.01, _far = 2000;*/
}