/*
Copyright (c) 2013 Andrey Penechko

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license the "Software" to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module anchovy.gui.controls.button;

import anchovy.gui.all;

class Button : Widget
{
public:
	this()
	{
		super();
		addEventHandler(&pointerPressed);
		addEventHandler(&pointerMoved);
		addEventHandler(&pointerEntered);
		addEventHandler(&pointerLeaved);
		addEventHandler(&pointerReleased);
		style = "button";
		_textLine = new TextLine("", null);
	}
	
	void caption(dstring newCaption) @property
	{
		_textLine.text = newCaption;
	}

	override void doDraw(IGuiRenderer renderer) 
	{
		renderer.drawControlBack(this, staticRect);
		assert(_textLine);
		renderer.pushClientArea(staticRect);

		int offx, offy;
		if (state == "pressed")
		{
			offx = 1;
			offy = 1;
		}
		renderer.drawTextLine(_textLine, staticRect, AlignmentType.CENTER_CENTER);
		renderer.popClientArea;
	}

	bool pointerPressed(PointerPressEvent event)
	{
		writeln("pointer press");
		//if (!staticRect.contains(event.pointerPosition)) return false;
		if (event.button == PointerButton.PB_LEFT)
		{
			event.gui.inputOwnerWidget = this;
			state = "pressed";
			return true;
		}
		return true;
	}

	bool pointerMoved(PointerMoveEvent event)
	{
		writeln("pointer move");
		if (!staticRect.contains(event.newPointerPosition))
		{
			if (event.gui.inputOwnerWidget is this)
				state = "normal";
			return false;
		}
		if (event.gui.inputOwnerWidget is this)
			state = "pressed";

		event.gui.hoveredWidget = this;
		return true;
	}

	bool pointerEntered(PointerEnterEvent event)
	{
		if (event.gui.inputOwnerWidget is this)
		{
			state = "pressed";
		}
		else
		{
			state = "hover";
		}
		return true;
	}
	
	bool pointerLeaved(PointerLeaveEvent event)
	{
		state = "normal";
		return true;
	}

	bool pointerReleased(PointerReleaseEvent event)
	{
		//
		if (event.button == PointerButton.PB_LEFT && event.gui.inputOwnerWidget is this)
		{
			event.gui.lastClickedWidget = this;
			event.gui.inputOwnerWidget = null;

			if (!staticRect.contains(event.pointerPosition))
			{
				event.gui.hoveredWidget = null;
				state = "normal";
				return true;
			}
			state = "hover";

			return true;
		}
		return true;
	}

	override protected void skinChanged()
	{
		writeln("button skin changed ", _skin, " ", _style);
		_textLine.font = getStyleFont(skin, style);
	}
	
	protected:
	TextLine _textLine;
}

