/*
Copyright (c) 2013 Andrey Penechko

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license the "Software" to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module anchovy.gui.controls.edit;

import std.algorithm;
import std.stdio;

import anchovy.gui.all;

class Edit : Widget
{
	this(Rect initRect, in string initStyleName = "edit", GuiSkin initSkin = null)
	{
		super(initRect, initStyleName, initSkin);
	}

	override bool keyPressed(in KeyCode key, KeyModifiers modifiers)
	{
		if (!_isEditable) return true;
		
		bool doTextUpdate = true;
		bool doDeselect = true;

		if (modifiers & KeyModifiers.CONTROL)
		{
			if (key == KeyCode.KEY_C)
			{
				window.clipboardString = copy();
				doDeselect = false;
			}		
			else if (key == KeyCode.KEY_V)
			{
				paste(window.clipboardString);
			}	
			else if (key == KeyCode.KEY_X)
			{
				window.clipboardString = copy();
				removeSelectedText();
			}
			else
			{
				doTextUpdate = false;
			}
		}
		else if (key == KeyCode.KEY_BACKSPACE)
		{
			if (_hasSelectedText)
			{
				removeSelectedText();
			}
			else if (_textLine.text.length > 0 && _cursorPos > 0)
			{
				_cursorRenderPos -= _textLine.font.getGlyph(_textLine.text[_cursorPos-1]).metrics.advanceX;
				_textLine.text = _textLine.text[0.._cursorPos-1] ~ _textLine.text[_cursorPos..$];
				--_cursorPos;
				onCursorMove();
			}
		}
		else if (key == KeyCode.KEY_LEFT)
		{
			moveCursorLeft();
		}
		else if (key == KeyCode.KEY_RIGHT)
		{
			moveCursorRight();
		}
		else if (key == KeyCode.KEY_DELETE)
		{
			if (_hasSelectedText)
			{
				removeSelectedText();
			}
			else if (_cursorPos < _textLine.text.length)
			{
				_textLine.text = _textLine.text[0.._cursorPos]~_textLine.text[_cursorPos+1..$];
				onCursorMove();
			}
		}
		else if (key == KeyCode.KEY_HOME)
		{
			setCursorPos(0);
		}
		else if (key == KeyCode.KEY_END)
		{
			setCursorPos(_textLine.text.length);
		}
		else
		{
			doTextUpdate = false;
		}
		
		if (doTextUpdate)
		{
			calcTextXPos();
			if (doDeselect)
			{
				deselect();
			}
		}
		
		return true;
	}
	
	override bool keyReleased(in KeyCode key, KeyModifiers modifiers)
	{
		return true;
	}

	/// Set current cursor blink interval in seconds.
	/// newInterval must be greater than zero.
	void blinkInterval(double newInterval) @property
	in
	{
		assert(newInterval > 0);
	}
	body
	{
		_blinkInterval = newInterval;
		if (_blinkTimer) _blinkTimer.delay = newInterval;
	}

	/// Get current cursor blink interval in seconds.
	double blinkInterval() @property
	{
		return _blinkInterval;
	}

	void paste(dstring text)
	{
		removeSelectedText();
		_textLine.text = _textLine.text[0.._cursorPos] ~ text ~ _textLine.text[_cursorPos..$];
		setCursorPos(_cursorPos + text.length);
	}
	
	override bool charEntered(in dchar chr)
	{
		if (_isEditable)
		{
			normalizeSelection();
			_textLine.text = _textLine.text[0.._selectionStart] ~ chr ~ _textLine.text[_selectionEnd..$];
			setCursorPos(_selectionStart+1);
			deselect();
			calcTextXPos();
		}

		return true;
	}

	dstring copy()
	{
		return selectedText();
	}

	override void drawContent(IGuiRenderer renderer) 
	{
		assert(_textLine);
		renderer.pushClientArea(_staticRect);
			renderer.renderer.setColor(Color(0,0,0));
			renderer.drawTextLine(_textLine, _staticRect.croppedByOffset(_contentOffset), AlignmentType.NONE_CENTER);
			if (_state == "focused" && _isCursorVisible && _isCursorBlinkVisible && window.inputOwnerWidget != this)
			{
				renderer.renderer.fillRect(Rect(_staticRect.x + _cursorRenderPos + _textLine.x + _contentOffset.left,
			                                	_staticRect.y + _staticRect.height/2 - _textLine.height/2,
			                                	1, _textLine.height));
			}
			if (_hasSelectedText)
			{
				renderer.renderer.setColor(Color(0,0,255, 64));
				uint selectionStartX = calcCharOffset(_selectionStart);
					renderer.renderer.fillRect(Rect(_staticRect.x + _textLine.x + _contentOffset.left + selectionStartX,
				                                	_staticRect.y + _staticRect.height/2 - _textLine.height/2,
					                               	calcCharOffset(_selectionEnd) - selectionStartX, _textLine.height));
			}
		renderer.popClientArea;
	}

	override void handleResize() @trusted
	{
		calcTextXPos();
	}

	override void focusGained()
	out
	{
		assert(_blinkTimer);
	}
	body
	{
		assert(_blinkTimer is null);
		assert(_isCursorBlinkVisible);
		_state = "focused";

		_blinkTimer = window.timerManager.addTimer(_blinkInterval, &onCursorBlink, double.nan, TimerTickType.PROCESS_LAST);
	}

	/// Used as a callback to blink timer.
	protected double onCursorBlink(double timesUpdated)
	{
		if ((timesUpdated % 2) > 0)
			_isCursorBlinkVisible = !_isCursorBlinkVisible;

		return 0;
	}
	
	override void focusLost()
	{
		_state = "normal";

		window.timerManager.stopTimer(_blinkTimer);
		_blinkTimer = null;

		_isCursorBlinkVisible = true;
	}

	dstring text() @property
	{
		if (_textLine is null) return "";
		return _textLine.text;
	}
	
	void text(dstring newText) @property
	{
		if (_textLine is null) return;
		return _textLine.text = newText;
	}

	dstring selectedText() @property
	{
		if (_selectionStart > _selectionEnd)
		{
			return _textLine.text[_selectionEnd.._selectionStart];
		}
		else
		{
			return _textLine.text[_selectionStart.._selectionEnd];
		}
	}

	override bool pointerPressed(ivec2 pointerPosition, PointerButton button)
	{
		if (!_staticRect.contains(pointerPosition)) return false;

		if (button == PointerButton.PB_LEFT)
		{
			window.focusedWidget = this;
			moveCursorToClickPos(pointerPosition);
			window.inputOwnerWidget = this;
			_selectionStart = _cursorPos;
			_selectionEnd = _cursorPos;
			return true;
		}

		return true;
	}

	override bool pointerReleased(ivec2 pointerPosition, PointerButton button)
	{
		if (!_staticRect.contains(pointerPosition) && window.inputOwnerWidget != this) return false;

		if (button == PointerButton.PB_LEFT)
		{
			window.inputOwnerWidget = null;
			return true;
		}
		
		return true;
	}

	override bool pointerMoved(ivec2 newPointerPosition)
	{
		if (window.inputOwnerWidget == this )
		{
			moveCursorToClickPos(newPointerPosition);
			_selectionEnd = _cursorPos;
			updateSelection();
			calcTextXPos();
		}

		return false;
	}

	void isEditable(bool editable) @property
	{
		_isEditable = editable;
	}

	bool isEditable() @property
	{
		return _isEditable = true;
	}

	void removeSelectedText()
	{
		normalizeSelection();
		_textLine.text = _textLine.text[0.._selectionStart] ~ _textLine.text[_selectionEnd..$];
		setCursorPos(_selectionStart);
		deselect();
	}

	void deselect()
	{
		_selectionStart = _cursorPos;
		_selectionEnd = _cursorPos;
		_hasSelectedText = false;
	}

	void select(uint start, uint end)
	{
		_selectionStart = start;
		_selectionEnd   = end;

		normalizeSelection();
		updateSelection();
	}

protected:

	/// Swaps _selectionStart and _selectionEnd if _selectionStart > _selectionEnd.
	/// Should be used before text editing.
	void normalizeSelection()
	{
		if (_selectionStart > _selectionEnd)
		{
			uint temp = _selectionEnd;
			_selectionEnd = _selectionStart;
			_selectionStart = temp;
		}
	}

	void updateSelection()
	{
		_selectionStart = clamp!uint(_selectionStart, 0, _textLine.text.length);
		_selectionEnd = clamp!uint(_selectionEnd, 0, _textLine.text.length);

		if (_selectionEnd - _selectionStart > 0)
			_hasSelectedText = true;
		else
			_hasSelectedText = false;
	}

	override void skinChanged()
	{
		_contentOffset = _skin[_styleName]["normal"].contentPadding;
		setTextLineFont();
	}

	void moveCursorToClickPos(ivec2 pointerPosition)
	in
	{
		assert(_textLine);
	}
	body
	{
		if (_textLine.text.length > 0)
		{
			int clickX = pointerPosition.x - (_staticRect.x + _contentOffset.left + _textLine.x);

			Font textFont = _textLine.font;
			int charCenter;
			int charX = 0;
			uint charIndex = 0;

			while (true)
			{
				charCenter = charX + (textFont.getGlyph(_textLine.text[charIndex]).metrics.advanceX/2);
				if (charCenter > clickX) break;

				charX += textFont.getGlyph(_textLine.text[charIndex]).metrics.advanceX;
				++charIndex;

				if (charIndex == _textLine.text.length) break;
			}

			_cursorPos = charIndex;
			_cursorRenderPos = charX;
		}
	}

	/// If cursor changes its position the blinking delay must be reset.
	void onCursorMove()
	{
		if (_blinkTimer)
		{
			window.timerManager.resetTimer(_blinkTimer);
			_isCursorBlinkVisible = true;
		}
	}

	void moveCursorRight()
	{
		if (_cursorPos < _textLine.text.length)
		{
			_cursorRenderPos += _textLine.font.getGlyph(_textLine.text[_cursorPos]).metrics.advanceX;
			++_cursorPos;
			onCursorMove();
		}
	}

	void moveCursorLeft()
	{
		if (_cursorPos > 0)
		{
			_cursorRenderPos -= _textLine.font.getGlyph(_textLine.text[_cursorPos-1]).metrics.advanceX;
			--_cursorPos;
			onCursorMove();
		}
	}

	void setCursorPos(uint position)
	{
		scope(exit) onCursorMove();

		if (position > _textLine.text.length)
		{
			_cursorPos = _textLine.text.length;
			_cursorRenderPos = _textLine.width;
			return;
		}
		else if (position < 0)
		{
			_cursorPos = 0;
			_cursorRenderPos = 0;
			return;
		}

		Font textFont = _textLine.font;
		int charX = 0;
		uint charIndex = 0;

		while (true)
		{
			if (charIndex == position) break;

			charX += textFont.getGlyph(_textLine.text[charIndex]).metrics.advanceX;
			++charIndex;
			
			if (charIndex == _textLine.text.length) break;
		}

		_cursorPos = charIndex;
		_cursorRenderPos = charX;
	}

	/// Returns offset in pixels from the begining of text
	uint calcCharOffset(uint index)
	{
		if (index > _textLine.text.length)
			return _textLine.width;

		int charX = 0;
		uint charIndex = 0;
		
		while (true)
		{
			if (charIndex == index) break;
			
			charX += _textLine.font.getGlyph(_textLine.text[charIndex]).metrics.advanceX;
			++charIndex;
		}

		return charX;
	}

	void calcTextXPos()
	{
		Rect textRect = _rect.croppedByOffset(_contentOffset);
		if (_textLine.width < textRect.width)
		{
			_textLine.x = 0;
		}
		else
		{
			if (_cursorRenderPos + _textLine.x > textRect.width || _cursorPos == _textLine.text.length)
			{
				_textLine.x = textRect.width - _cursorRenderPos;
			}
			else if (_cursorRenderPos + _textLine.x < 0)
			{
				_textLine.x = -_cursorRenderPos;
			}
			else if (_textLine.x + _textLine.width < textRect.width)
			{
				_textLine.x = textRect.width - _textLine.width;
			}
		}
	}

private:

	RectOffset _contentOffset;
	bool _isEditable = true;
	bool _isCursorVisible = true;
	bool _hasSelectedText = false;

	/// When blinking if true and _isCursorVisible is true, then cursor will be visible.
	bool _isCursorBlinkVisible = true;

	/// if there is no current selection _selectionStart and _selectionEnd are equal to _cursorPos.
	uint _selectionStart, _selectionEnd;

	int _cursorPos = 0;
	int _cursorRenderPos = 0;

	double _blinkInterval = 0.25f;

	/// Used for cursor blinking.
	Timer _blinkTimer;
}
