/*
Copyright (c) 2013 Andrey Penechko

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license the "Software" to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module anchovy.gui.controls.list;

import std.math;

import anchovy.gui.all;

class List : GuiWidgetContainer
{
	this(Rect initRect, in string initStyleName = "edit", GuiSkin initSkin = null)
	{
		super(initRect, initStyleName, initSkin);
	}
	
	override void init()
	{
		addWidget(new VScrollbar(Rect(0,0,0,0)));
		_minSize = uvec2(200, 200);
	}
	
	override void drawBackground(IGuiRenderer guirenderer) 
	{
		guirenderer.drawControlBack(this, _staticRect);
	}
	
	override void handleResize() @trusted
	{
		applySizeConstraints();
	}

	override void drawContent(IGuiRenderer guirenderer)
	{
		guirenderer.pushClientArea(_staticRect);
		guirenderer.renderer.setColor(Color(0, 0, 0, 255));
		int y = canvasY;
		foreach(ref line; _textCache)
		{
			guirenderer.drawTextLine(line, _staticRect.x, _staticRect.y + y, AlignmentType.LEFT_TOP);
			y += _lineGap + _fontHeight;
		}
		_children[0].draw(guirenderer);
		guirenderer.popClientArea();
	}

	void append(string newItem)
	{
		_items ~= newItem;
		_textCache ~= new TextLine(to!dstring(newItem), _font);
		writeln("appended: ", newItem);
	}
	
	string[] clear()
	{
		auto items = _items;
		_items = [];
		discardTextCache();
		return items;
	}

	string opIndex(size_t index)
	{
		if (index >= _items.length)
			return null;

		return _items[index];
	}

protected:

	override void skinChanged()
	{
		Font newFont = getStyleFont(_skin, styleName);
		if (newFont != _font)
		{
			_font = newFont;
			_lineGap = _font.lineGap;
			_fontHeight = _font.size;
			discardTextCache();
		}
		foreach (widget; _children)
		{
			widget.handleParentSkinChange();
		}
		updateComponents();
	}

	void discardTextCache()
	{
		_textCache = [];
	}
	
	void updateComponents()
	{
		writeln(_rect.width," ", _children[0].width);
		_children[0].x = _rect.width - _children[0].width;
		_children[0].height = _rect.height;
	}

	void updateTextCache()
	{
		uint firstCached = _firstVisibleIndex; 
		uint lastCached = firstCached + _textCache.length;
		
		uint newFirstCached = -canvasY;
		uint newLastCached = newFirstCached + _maxVisibleLines;
		if (newLastCached >= _items.length)
			newLastCached = _items.length-1;
	}
	
	uint calcMaxVisibleLines() @property
	{
		return cast(uint)ceil(_rect.height / cast(float)(_fontHeight + _lineGap));
	}

	/// index of string in _items which is at top position in viewport
	/// must be < _items.length
	uint _firstVisibleIndex;
	TextLine[] _textCache;
	string[] _items;

	uint _lineGap;
	uint _fontHeight;
	
	
	uint _maxVisibleLines;
	
	int canvasX, canvasY;

	Font _font;
}

