/*
Copyright (c) 2013 Andrey Penechko

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license the "Software" to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module anchovy.graphics.interfaces.irenderer;

private import std.stdio;
public import anchovy.graphics.texrectarray;
public import anchovy.graphics.font.fontmanager;

private {
	import std.stdio;
	import std.string;
	//import anchovy.graphics.mesh;
	import anchovy.core.types;
	import anchovy.graphics.texture;
	import anchovy.graphics.shaderprogram;
}

interface IRenderer
{
	void bindShaderProgram(uint shaderName);
	void bindShaderProgram(ref ShaderProgram program);
	//void renderMesh(Mesh mesh);
	Texture createTexture(string filename);
	void bindTexture(Texture texture, uint textureUnit = 0);
	void enableAlphaBlending();
	void disableAlphaBlending();
	uint createShaderProgram(string vertexSource, string fragmentSource);
	uint registerShaderProgram(ShaderProgram program);
	void drawRect(Rect rect);
	void fillRect(Rect rect);
	final void drawTexRect(Rect target, ivec2 sourcePos, Texture texture)
	{
		drawTexRect(target, Rect(sourcePos, target.size), texture);
	}
	void drawTexRect(Rect target, Rect source, Texture texture);
	void drawTexRectArray(TexRectArray array, ivec2 position, Texture texture, ShaderProgram customProgram = null);
	void setColor(in Color newColor);
	void setColor(in Color4f newColor);
	void setClearColor(in Color color);
	uvec2 windowSize();
	void flush();
	void close();
}
