/*
Copyright (c) 2013 Andrey Penechko

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license the "Software" to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module anchovy.graphics.font.fontmanager;


import anchovy.core.types;
import anchovy.graphics.texture;
public import anchovy.graphics.font.font;
import anchovy.graphics.font.textureatlas;


static const dchar[] asciiChars = "0123456789!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz ";

class FontManager
{
	this()
	{
		texAtlas = new TextureAtlas(standartAtlasSize, standartAtlasSize);
		cache ~= asciiChars;
		texture = new Texture(texAtlas.getBitmap, TextureTarget.target2d, TextureFormat.r);
		fonts = new IdArray!Font;
	}

	uint createFont(in string filename, in uint size)
	{
		Font newFont = new Font(filename, texAtlas, cache.idup, size);

		uint newId = fonts.add(newFont);

		texture.invalidate();

		return newId;
	}

	Texture getFontAtlasTex()
	{
		return texture;
	}

	Font getFont(in uint id)
	{
		return fonts[id];
	}

	ref dchar[] charCache() @property
	{
		return cache;
	}

private:

	static const ushort standartAtlasSize = 256;

	dchar[] cache;
	IdArray!Font fonts;
	TextureAtlas texAtlas;
	Texture texture;
}
