/*
Copyright (c) 2013 Andrey Penechko

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license the "Software" to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module anchovy.utils.flexibleobject.flexibleobject;

import std.variant : Variant;

import anchovy.utils.flexibleobject.flexibleproperty : IProperty, ValueProperty;
import anchovy.utils.flexibleobject.flexibleaccess;
import anchovy.utils.signal : Signal;

// Object that can have any number of properties
class FlexibleObject
{
	override int opCmp(Object o) { return cast(int)cast(void*)this - cast(int)cast(void*)o; }

	package IProperty[string] properties;

	Variant opIndex(string propName)
	{
		return properties.get(propName, new ValueProperty(this, Variant(null))).value;
	}

	Variant opIndexAssign(V)(V value, string propName)
	{
		static if (is(V:IProperty) && !is(V == typeof(null)))
		{
			return properties[propName] = value;
		}
		else static if (is(V:Variant))
		{
			if (auto property = propName in properties)
			{
				return property.value = value;
			}
			else
			{
				return properties[propName] = new ValueProperty(this, value);
			}
		}
		else
		{
			if (auto property = propName in properties)
			{
				return property.value = Variant(value);
			}
			else
			{
				return properties[propName] = new ValueProperty(this, Variant(value));
			}
		}
	}

	Variant opIndexOpAssign(string op, V)(V value, string propName)
	{
		IProperty property = properties.get(propName, new ValueProperty(this, Variant(null)));

		mixin("property.value " ~ op ~ "= value;");

		return property.value;
	}

	Variant remove(string propName)
	{
		Variant result = properties.get(propName, new ValueProperty(this, Variant(null))).value;

		properties.remove(propName);

		return result;
	}

	IProperty property(string propName)
	{
		if (propName !in properties)
		{
			properties[propName] = new ValueProperty(this, Variant(null));
		}

		return properties[propName];
	}
}
