/*
Copyright (c) 2013 Andrey Penechko

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license the "Software" to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module anchovy.core.interfaces.iwindow;

public import anchovy.core.types;

abstract class IWindow
{
	void init(in uint width, in uint height, in string caption);
	void reshape(in uint width, in uint height);
	void processEvents();
	double getTime(); //in seconds
	void swapBuffer();
	void releaseWindow();

	void setMousePosition(in int x, in int y);
	ivec2 getMousePosition();

	void grabMouse();
	void releaseMouse();

	ivec2 getSize();

	bool isKeyPressed(uint key);
	@property nothrow
	{
		uint width();
		uint width(in uint newWidth);

		uint height();
		uint height(in uint newHeight);
	}

	string getClipboard();
	void setClipboard(string newClipboardString);
	nothrow
	{
		void focusChanged(in bool focusObtained){}
		void keyPressed(in uint keyCode){}
		void keyReleased(in uint keyCode){}
		void charPressed(in dchar unicode){}
		void charReleased(in dchar unicode){}
		void mousePressed(in uint mouseButton){}
		void mouseReleased(in uint mouseButton){}
		void mouseMoved(in int newX, in int newY){}
		void windowResized(in uint newWidth, in uint newHeight){}
		void windowMoved(in int newX, in int newY){}
		void windowIconified(in bool iconified){}
		void wheelScrolled(in double scrollX, in double scrollY){}
	}
	bool quit() nothrow
	{
		return true;
	}
}