/*
Copyright (c) 2013 Andrey Penechko

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license the "Software" to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module anchovy.graphics.font.textureatlas;

import std.stdio;

import anchovy.utils.rectbinpacker;
import anchovy.graphics.texture;
import anchovy.graphics.bitmap;
import anchovy.core.math;
import anchovy.core.types;


class InsertException : Exception
{
	this(string msg, string file = __FILE__, size_t line = __LINE__)
	{
		super(msg, file, line);
	}
}

/// Can be used to tightly store small images in big atlas, such as font glyps, or lightmaps etc.
class TextureAtlas
{
	this(in uint size)
	{
		binPacker = new RectBinPacker(size, size);
		bitmap = new Bitmap(size, size, 1);
	}

	this(in uint width, in uint height)
	{
		binPacker = new RectBinPacker(width, height);
		bitmap = new Bitmap(width, height, 1);
	}

	/++
	 + Returns: position of inserted node, or throws if not enough space
	 +/
	uvec2 insert(in uint width, in uint height)
	{
		Node* node = binPacker.insert(width, height);

		if (node is null) // There is no place to put new item.
		{
			if (_autoGrow) // Atlas can grow.
			{
				if (bitmap.size.x >= bitmap.size.y) // Growing vertically.
				{
					if (bitmap.size.y >= _maxAtlasSize)
					{
						throw new InsertException("Texture atlas is full. Max atlas size reached");
					}

					bitmap.data ~= new ubyte[bitmap.size.y*bitmap.size.x];
					delete binPacker;
					binPacker = new RectBinPacker(bitmap.size.x, bitmap.size.y, 0, bitmap.size.y);
					bitmap.size.y *= 2;
				}
				else // Growing horizontally.
				{
					ubyte[] newData = new ubyte[bitmap.size.y*bitmap.size.x*2];
					for(uint y = 0; y < bitmap.size.y; ++y)
					{
						newData[bitmap.size.x*y*2..bitmap.size.x*y*2+bitmap.size.x] = bitmap.data[bitmap.size.x*y..bitmap.size.x*(y+1)];
					}

					delete bitmap.data;
					bitmap.data = newData;
					delete binPacker;
					binPacker = new RectBinPacker(bitmap.size.x, bitmap.size.y, bitmap.size.x, 0);
					bitmap.size.x *= 2;
				}

				node = binPacker.insert(width, height);
			}
			else
			{
				throw new InsertException("Texture atlas is full");
			}
		}

		return uvec2(node.rect.x, node.rect.y);
	}

	/// Returns internal bitmap.
	ref Bitmap getBitmap()
	{
		return bitmap;
	}

	/// Sets grow policy.
	bool autoGrow(in bool allowAutoGrow) @property
	{
		return _autoGrow = allowAutoGrow;
	}

	/// Returns grow policy.
	bool autoGrow() @property
	{
		return _autoGrow;
	}

private:

	bool _autoGrow = true;
	uint _maxAtlasSize = 8192; // 2^13

	Bitmap bitmap;
	RectBinPacker binPacker;
}
