/*
Copyright (c) 2013 Andrey Penechko

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license the "Software" to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module anchovy.gui.layouts.linearlayout;

import anchovy.gui.all;

public import anchovy.gui.interfaces.ilayout;

class LinearLayout(bool vertical) : ILayout
{
	uint spacing = 2; // Between children
	uint padding = 2; // Between borders and content

	override void minimize(Widget root)
	{
		Widget[] children = root.getPropertyAs!("children", Widget[]);
		ivec2 rootSize = root.getPropertyAs!("userSize", ivec2);

		uint minRootWidth = uint.max; // Will be max child width. Then padding will be added
		uint minRootLength = padding * 2;
		uint childrenLength;
		uint numExpandableChildren;

		foreach(child; children)
		{
			ivec2 childSize = child.getPropertyAs!("prefSize", ivec2);
			childrenLength += *(childSize.length);
			minRootWidth = maxWidth(childSize, rootSize);

			if (child.peekPropertyAs!("isExpandable")) ++numExpandableChildren;

			minRootLength += spacing;
		}

		minRootLength += childrenLength;
		minRootWidth += padding * 2;

		*(rootSize.width) = minRootWidth;
		*(rootSize.length) = minRootLength;

		root.setProperty!("prefSize")(rootSize);
		root.setProperty!("numExpandable")(numExpandableChildren);
	}

	override void expand(Widget root)
	{
		Widget[] children = root.getPropertyAs!("children", Widget[]);
		uint numExpandableChildren = root.getPropertyAs!("numExpandable", uint);

		foreach(child; children)
		{
			
		}
	}

	override void onContainerResized(Widget root, ivec2 oldSize, ivec2 newSize)
	{
	}

private:

	static pure int* length(ivec2 vector)
	{
		static if (vertical)
			return &vector.y;
		else
			return &vector.x;
	}

	static pure int* width(ivec2 vector)
	{
		static if (vertical)
			return &vector.x;
		else
			return &vector.y;
	}

	static pure int maxWidth(ivec2 a, ivec2 b)
	{
		static if (vertical)
			return a.x > b.x ? a.x : b.x;
		else
			return a.y > b.y ? a.y : b.y;
	}
}