/*
Copyright (c) 2013 Andrey Penechko

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license the "Software" to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module anchovy.gui.interfaces.iguirenderer;

public import anchovy.graphics.interfaces.irenderer;

import anchovy.gui.all;

enum HoriAlignment
{
	NONE   = 1,
	LEFT   = 2,
	CENTER = 4,
	RIGHT  = 8,
}

enum VertAlignment
{
	NONE   = 16,
	TOP    = 32,
	CENTER = 64,
	BOTTOM = 128,
}

enum AlignmentType
{
	NONE_NONE   = HoriAlignment.NONE | VertAlignment.NONE,
	NONE_TOP    = HoriAlignment.NONE | VertAlignment.TOP,
	NONE_CENTER = HoriAlignment.NONE | VertAlignment.CENTER,
	NONE_BOTTOM = HoriAlignment.NONE | VertAlignment.BOTTOM,

	LEFT_NONE    = HoriAlignment.LEFT | VertAlignment.NONE,
	LEFT_TOP    = HoriAlignment.LEFT | VertAlignment.TOP,
	LEFT_CENTER = HoriAlignment.LEFT | VertAlignment.CENTER,
	LEFT_BOTTOM = HoriAlignment.LEFT | VertAlignment.BOTTOM,
	
	CENTER_NONE    = HoriAlignment.CENTER | VertAlignment.NONE,
	CENTER_TOP    = HoriAlignment.CENTER | VertAlignment.TOP,
	CENTER_CENTER = HoriAlignment.CENTER | VertAlignment.CENTER,
	CENTER_BOTTOM = HoriAlignment.CENTER | VertAlignment.BOTTOM,

	RIGHT_NONE    = HoriAlignment.RIGHT | VertAlignment.NONE,
	RIGHT_TOP    = HoriAlignment.RIGHT | VertAlignment.TOP,
	RIGHT_CENTER = HoriAlignment.RIGHT | VertAlignment.CENTER,
	RIGHT_BOTTOM = HoriAlignment.RIGHT | VertAlignment.BOTTOM,
}

interface IGuiRenderer
{
	uint getFontTexture();
	ref FontManager fontManager() @property;
	void drawControlBack(GuiWidget widget, Rect staticRect);

	/// draws text line with alignment specified relative to point
	void drawTextLine(ref TextLine line, in int x, in int y, in AlignmentType alignment);

	/// draws text line with alignment specified relative to rectangle
	void drawTextLine(ref TextLine line, in Rect area, in AlignmentType alignment);
	void pushClientArea(Rect area);
	void popClientArea();
	void setClientArea(Rect area);
	IRenderer renderer() @property;
}