/*
Copyright (c) 2013 Andrey Penechko

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license the "Software" to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module anchovy.gui.controls.internals.draggable;

import anchovy.gui.all;

alias void delegate(IWidget widget, ref ivec2 deltaPosition) OnDragHandler;

class Draggable : Widget
{
	this(Rect initRect, in string initStyleName = "none", GuiSkin initSkin = null)
	{
		super(initRect, initStyleName, initSkin);
	}

	override bool pointerPressed(ivec2 pointerPosition, PointerButton button)
	{
		if (!_staticRect.contains(pointerPosition)) return false;
		if (button == PointerButton.PB_LEFT && _isDraggable)
		{
				window.inputOwnerWidget = this;
				_dragPosition = pointerPosition;
				return true;
		}
		return false;
	}
	
	override bool pointerMoved(ivec2 newPointerPosition)
	{
		if (window.inputOwnerWidget is this)
		{
			ivec2 deltaPos = newPointerPosition - _dragPosition;
			_dragPosition = newPointerPosition;

			if (_onDrag) _onDrag(this, deltaPos);

			_rect.move(deltaPos);
			calcStaticRect(_parent.staticRect);

			return true;
		}
		return false;
	}
	
	override bool pointerReleased(ivec2 pointerPosition, PointerButton button)
	{
		if (window.inputOwnerWidget is this)
		{
			window.inputOwnerWidget = null;
		}
		if (!_staticRect.contains(pointerPosition)) return false;

		return true;
	}

	@property
	{
		bool isDraggable(bool draggable)
		{
			return _isDraggable = draggable;
		}

		bool isDraggable()
		{
			return _isDraggable;
		}
	}

	@property
	{
		///
		OnDragHandler onDrag(OnDragHandler newHandler)
		{ 
			return _onDrag = newHandler;
		}
		/// ditto
		OnDragHandler onDrag()
		{ 
			return _onDrag;
		}
	}

protected:

	bool _isDraggable = true;

	/// Used for calculating dragging delta position.
	ivec2 _dragPosition;

	OnDragHandler _onDrag;
}

